#!/bin/bash
# ------------------------------------------------ +
# file: pub_func 
# ------------------------------------------------ +
# @author <github.com/cunwang>
# @date	2015/03/16 - 03/20
# @edit date	2018/08/17
# @version 1.2
# ------------------------------------------------ +

:<<!
Debug Model, To be extended, default 0.
!
IS_DEBUG=0;

:<<!
Max thread , 
If Thread nums bigger than the Max Thread will be ignore. 
!
TASK_MAX_THREAD=2;

:<<!
Number of tasks supported at the same time.
According to the actual situation of rational allocation, default 2.
!
TASK_MAX_NUM=2;

:<<!
Set Default Config Path.
!
PHP_BIN_PATH="/usr/local/php/bin/php";
SHELL_BIN_PATH="/bin/bash";
CONFIG_NAME="./config";
CONFIG_TASK_PATH="./task/";
CONFIG_LOG_PATH="./runtime/";
CONFIG_PIPE_PATH="./pipe/";
CONFIG_CORE_SCRIPT="task.sh";

:<<!
Variable initialization.
!
HANDLE_FLAG=1;
SORT_MODEL='';
DAYS='';
STEP_MODEL='int';
STEP_DATE_BASE=3600;
STEP_DATE_FORMAT="%Y-%m-%d";
STEP_NUM_BASE=1;
DATE_REGEXP="^[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}";

script_type=0;
script_path=0;
script_start=0;
script_end=0;
script_step=1;
script_thread=2;


:<<!
[Function] 
@abstract, Recorded String to file
@params, $1 String
@usage
	> log_it "record something."
!
function log_it()
{
	if [ $IS_DEBUG -eq 1 ]; then
		local now="`date +'%Y-%m-%d %H:%M:%S'`";
		local logName="`date +'%Y%m%d'`-run.log";
		echo -e "${now}\t${1}" >>  "${CONFIG_LOG_PATH}${logName}";
	fi
}

function getInterpreter()
{
	local interPreter="";
	case "$1" in
		php)
			interPreter=${PHP_BIN_PATH};
		;;

		shell)
			interPreter=${SHELL_BIN_PATH};
		;;
	esac
	throw "${interPreter}";
}

function debug()
{
	log_it "\033[31;31merror: [@ Line $LINENO] Error: Command or function exited width status $?!\033[0m";
}

function killAll()
{
	if [ "`ls -A ${CONFIG_PIPE_PATH}`" != "" ]; then 
		/bin/rm ${CONFIG_PIPE_PATH}*;
	fi

	/bin/ps ajx | 
		grep "${CONFIG_CORE_SCRIPT}" | 
			grep -v grep | 
				awk '{print $2}' | 
					while read subThread; 
					do 	
						echo "will kill the thread :${subThread}"; 
						killTask $subThread
					done;
	throw "All the Task is Stop!";
}

function killTask ()
{
	/bin/kill -9 $1;	
}

function iexit ()
{
	exit -1;
}

function throwANDexit()
{
	echo -e "$1";
	exit -1;
}

function throw ()
{
	echo  "${1}";
}

function getPipeByTask ()
{
	local task_pipe;
	task_pipe="${CONFIG_PIPE_PATH}${1}.fifo";
	createPipe "${task_pipe}";
	throw ${task_pipe};
}

function check_env()
{
	[[ ! -d "${CONFIG_NAME}" ]] && throwANDexit "Config folder not exists, please check!";
	[[ ! -d "${CONFIG_LOG_PATH}" ]] && throwANDexit "runtime folder not exists, please check!";
	[[ ! -d "${CONFIG_PIPE_PATH}" ]] && throwANDexit "pipe folder not exists, please check!";
}

function createPipe()
{
	if [ ! -e "${1}" ]; then
		mkfifo "${1}";
		log_it "[log] ${1} is create success!";
	else
		log_it "[log] ${1} is exists!";
	fi
}

function step_model_valid()
{
	if [[ "$START" =~ $DATE_REGEXP ]] && [[ "$_MAX" =~ $date_preg ]]; then
		STEP_MODEL='date';
		START=`date -d "${START}" +%s`
		_MAX=`date -d "${_MAX}" +%s`

		if [[ `expr $STEP % $STEP_DATE_BASE` != 0 ]]; then
			throwANDexit "Date type Script step must be divisible by ${STEP_DATE_BASE}!"
		fi
	fi

	[[ "${START}" -gt "${_MAX}" ]] && SORT_MODEL='desc' || SORT_MODEL='asc';
}
